### ISSUE TITLE
Doesn't work on WIn 7

### ISSUE THREAD

**Issue by cecrr** [andy-portmen/auto-shutdown#2]
Appears to install ok, but get an error "REG is not a recognisable command....)
Countdown window appears when triggered, gets to zero, then a box appears saying "one more step"

I note that in the test facility, when testing the connection, a green popup appears stating the native client, except the page doesn't appear. Your instructions suggest that this means the path is incorrect is says "(path is not correct in the options page)". However, there is no path in the options page and therefore no way of correcting this error (if that is indeed the cause.

I'm open to suggestions as to how to fix it.

**Comment by andy-portmen** [comment]
> but get an error "REG is not a recognisable command....)

If you get this error, please add `set PATH="%SYSTEM32%;PATH"` to the first line of the install.bat and retry. Do you still get that not found message?
