### ISSUE TITLE
"One last step" displayed although client is installed

### ISSUE THREAD

**Issue by Luke-Baker** [andy-portmen/auto-shutdown#3]
Windows 10 x64
Firefox 58.0a1, build 20171003220138
Auto Shutdown 0.1.1

In the Auto Shutdown NG 0.9.21 add-on, I had a custom command to execute, which I tried using in your add-on as well:
`C:\Windows\System32\schtasks.exe /run /tn "TaskNameGoesHere"`

Once the countdown reaches zero, it's replaced by the "One last step" message. Clicking the "Check connection" button shows a green checkmark with native client 0.5.0. Based on the output of the Browser Console that I pasted below, it seems the add-on is mangling the path:
```
GET https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Unnamed_subtropical_storm_%282005%29.jpg/150px-Unnamed_subtropical_storm_%282005%29.jpg 
[HTTP/2.0 200 OK 0ms]
TypeError: invalid 'in' operand browser[Learn More]  tabbrowser.xml:2431:1
NS_ERROR_NOT_INITIALIZED: Component returned failure code: 0xc1f30001 (NS_ERROR_NOT_INITIALIZED) [nsIMessageSender.sendAsyncMessage]  ext-windows.js:19
stderr output from native app com.add0n.node: events.js:160
stderr output from native app com.add0n.node:       throw er; // Unhandled 'error' event
stderr output from native app com.add0n.node:       ^
stderr output from native app com.add0n.node: 
stderr output from native app com.add0n.node: Error: spawn C:WindowsSystem32schtasks.exe ENOENT
stderr output from native app com.add0n.node:     at exports._errnoException (util.js:1018:11)
stderr output from native app com.add0n.node:     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
stderr output from native app com.add0n.node:     at onErrorNT (internal/child_process.js:367:16)
stderr output from native app com.add0n.node:     at _combinedTickCallback (internal/process/next_tick.js:80:11)
stderr output from native app com.add0n.node:     at process._tickCallback (internal/process/next_tick.js:104:9)
TelemetryStopwatch: key "FX_TAB_SWITCH_UPDATE_MS" was already initialized  TelemetryStopwatch.jsm:358
TypeError: newBrowser is undefined[Learn More]  tabbrowser.xml:1245:18
Unchecked lastError value: Error: An unexpected error occurred  ExtensionCommon.jsm:407
```
This should be handled properly, since that's how executables are specified on Windows (e.g. in shortcuts on the Start menu). There should also be an appropriate error message when there's a problem with the specified command.

I managed to get the command to launch by modifying it as follows:
`schtasks /run /tn "TaskNameGoesHere"`

**Comment by andy-portmen** [comment]
`C:\Windows\System32\schtasks.exe /run /tn "TaskNameGoesHere"` should work on 0.1.2. Please reopen if not. Thanks for the report.

**Comment by Luke-Baker** [comment]
Thank you. I've verified that it works.
