### ISSUE TITLE
Countdown window sticks around after execution

### ISSUE THREAD

**Issue by Luke-Baker** [andy-portmen/auto-shutdown#4]
Windows 10 x64
Firefox 58.0a1, build 20171003220138
Auto Shutdown 0.1.1

I ran a custom command and the countdown window stuck around showing 00 afterwards. It would be nice if it closed once the command has been executed successfully.

**Comment by andy-portmen** [comment]
There is a new option in 0.1.2 to allow closing of the countdown window if the external command execution is successful (return code is 0).

**Comment by Luke-Baker** [comment]
I'm afraid I couldn't get the option to work. Based on the Browser Console, it would seem Firefox doesn't think the add-on should be allowed to close the window:
```
GET https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Bluebonnet-8100.jpg/375px-Bluebonnet-8100.jpg [HTTP/2.0 200 OK 0ms]
TypeError: invalid 'in' operand browser[Learn More]  tabbrowser.xml:2431:1
NS_ERROR_NOT_INITIALIZED: Component returned failure code: 0xc1f30001 (NS_ERROR_NOT_INITIALIZED) [nsIMessageSender.sendAsyncMessage]  ext-windows.js:19
Scripts may not close windows that were not opened by script.  index.js:27:4
```

Firefox 58.0a1 build 20171004220309
Auto Shutdown 0.1.2

**Comment by andy-portmen** [comment]
Okay I checked it in Chrome and it worked! 0.1.3 is working in FF too. Thanks for the report.

**Comment by Luke-Baker** [comment]
Thank you. I've verified that it works.

Firefox 58.0a1 build 20171005220204
Auto Shutdown 0.1.3
