### ISSUE TITLE
Improvement

### ISSUE THREAD

**Issue by dittbub** [andy-portmen/auto-shutdown#9]
Hello,

I like the app but I think a better idea is to disable sleep mode while downloads are active and then re-enable sleep mode when there are no active downloads (just like a video playing might do)

https://developer.chrome.com/apps/power

Is this doable?

Thanks!

**Comment by andy-portmen** [comment]
We are going to have this if the browser supports `chrome.power` API. This option is enabled by default but can be disabled from the options page. Thanks for the report.
